language: rust
rust:
  - nightly-2017-08-13

services:
  - postgresql

before_install:
  # SCSS compiler
  - gem install sass

  # install diesel_cli if it's not cached
  - hash diesel 2>/dev/null || cargo install -f diesel_cli

before_script:
  - cp ci/.env.travis .env
  - diesel setup

env:
  - RUSTFLAGS="--deny warnings"

script: |
  ci/check-basic-style.sh && \
  cargo build --verbose && \
  cargo test --verbose

cache: cargo
