language: rust
rust:
  - nightly-2017-09-04

services:
  - postgresql

before_install:
  # SCSS compiler
  - gem install sass

  # Install NPM dependencies
  - cd ts/ && npm install && cd ..

  # install diesel_cli if it's not cached
  - hash diesel 2>/dev/null || cargo install -f diesel_cli

before_script:
  - cp ci/.env.travis .env
  - diesel setup

env:
  - RUSTFLAGS="--deny warnings"

script: |
  ci/check-basic-style.sh && \
  cargo build --verbose && \
  cargo test --verbose

cache:
  cargo: true
  directories:
    - ts/node_modules # NPM packages
